import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Router from 'next/router';
import Cookies from 'js-cookie'
import nextCookie from 'next-cookies';
import Spinner from '../components/Spinner/Spinner';
export default function Home() {
  const [loading,setLoading] = useState(true)
  const [user,setUser] = useState('')
  useEffect(()=>{
   const userCred = Cookies.get('user')||''
   if(!userCred){
     Router.push('/login')
   }
   else{
    setUser(JSON.parse(userCred))
    setLoading(false)
   }
  },[])

  const onLogout=()=>{
     Cookies.set('user','')
      Router.push('/login')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{loading&&<Spinner />}
      {
        !loading &&
        <main className={styles.main}>
        <h1 className={styles.title}>
         Welcome 
        
        
        </h1>
        <p>{user.email}</p>
        {
          user.email?
        <button onClick={onLogout}>
          Logout
        </button>
        :
        <Link href="/login">
        <a  className={styles.title}>Login</a>
         </Link>
        }
        
      </main>
      }
        
    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  const user = nextCookie(ctx)
  console.log(user)

  return{
    user
  }

}